version: '3'

services:
  auth-service:

    container_name: coveragex-authentication-service
    image: sabin2000/coveragex-authentication-service
    build:
      context: ../backend/services/authentication
      dockerfile: Dockerfile

    restart: always

    ports:
      - "5100:5100"
      
    volumes:
       - /app/node_modules
       - ../backend/services/authentication:/app

  analytics-service:
    container_name: coveragex-analytics-service
    image: sabin2000/coveragex-analytics-service

    build:
      context: ../backend/services/analytics
      dockerfile: Dockerfile

    restart: always
  
    ports:
      - "5101:5101"

    volumes:
      - /app/node_modules
      - ../backend/services/analytics:/app

  policies-service:
    container_name: coveragex-policies-service
    image: sabin2000/coveragex-policies-service

    build:
      context: ../backend/services/policies
      dockerfile: Dockerfile

    restart: always

    ports:
      - "5102:5102"

    volumes:
      - /app/node_modules
      - ../backend/services/policies:/app

  claims-service:
    container_name: coveragex-claims-service
    image: sabin2000/coveragex-claims-service

    build:
      context: ../backend/services/claims
      dockerfile: Dockerfile

    restart: always

    ports:
      - "5103:5103"

    volumes:
      - /app/node_modules
      - ../ackend/services/claims:/app