version: '3'

services:
  auth-service:

    container_name: coveragex-authentication-service
    image: sabin2000/coveragex-authentication-service
    build:
      context: ../backend/services/authentication
      dockerfile: Dockerfile

    restart: always

    ports:
      - "5100:5100"
      
    volumes:
       - /app/node_modules
       - ../backend/services/authentication:/app