export const REGISTER_USER_REQUEST = "REGISTER_USER_REQUEST";
export const REGISTER_USER_SUCCESS = "REGISTER_USER_SUCCESS";
export const REGISTER_USER_FAIL = "REGISTER_USER_FAIL";

export const VERIFY_EMAIL_ADDRESS_REQUEST = "VERIFY_EMAIL_ADDRESS_REQUEST"
export const VERIFY_EMAIL_ADDRESS_SUCCESS = "VERIFY_EMAIL_ADDRESS_SUCCESS";
export const VERIFY_EMAIL_ADDRESS_FAIL = "VERIFY_EMAIL_ADDRESS_FAIL";

export const LOGIN_USER_REQUEST = "LOGIN_USER_REQUEST";
export const LOGIN_USER_SUCCESS = "LOGIN_USER_SUCCESS";
export const LOGIN_USER_FAIL = "LOGIN_USER_FAIL";