export const FETCH_ALL_POLICIES_REQUEST = "FETCH_ALL_POLICIES_REQUEST";
export const FETCH_ALL_POLICIES_SUCCESS = "FETCH_ALL_POLICIES_SUCCESS";
export const FETCH_ALL_POLICIES_FAIL = "FETCH_ALL_POLICIES_FAIL";